### ISSUE TITLE
setChatHistory() in node-llama-cpp-v3 

### ISSUE THREAD

**Issue by scenaristeur** [nathanlesage/local-chat#5]
Hi @nathanlesage thxs for your help on https://github.com/withcatai/node-llama-cpp/pull/105#issuecomment-1981826680 

you use session.setChatHistory() https://github.com/nathanlesage/local-chat/blob/45c7d6b80c3e1bb566778ac195d8e87ec46558db/src/main/LlamaProvider.ts#L210, but i can not find where this function is defined ? could you help me , please

**Comment by nathanlesage** [comment]
I basically just searched the tree of node llama cpp. It's a bit difficult but it's manageable. Basically, how node llama cpp treats the models is the following:

1. You instantiate a session using context and loaded model
2. During instantiation, you can already provide a system prompt, unless you want to use the default one
3. Afterwards, you basically need to provide any messages prior to when the prompt will come, in a form as I did in my source code. There is an issue with the function calling that makes it iffy, but if you don't use it it's relatively straight forward, I have commented the appropriate part of the code.

Lastly, please don't open issues here if you have questions regarding the source code. Instead, please use another channel -- for quicker communication, feel free to join the Zettlr discord where you can reach me more quickly: https://go.zettlr.com/discord
