### ISSUE TITLE
Mouse focus stealing

### ISSUE THREAD

**Issue by Petemir** [nathanlesage/local-chat#6]
Hello!

I just downloaded the app and was about to start testing it. While trying to download a model (opening a tab in a browser in another window), I noticed that the mouse periodically (every ~10 seconds) returned to the application. As my window manager is set to change the window focus to where the mouse is, this can be problematic.

I have a multi-monitor (3 monitors) setup with a tiling window manager (i3) running on Kubuntu 23.10, and I have the latest localchat version (v0.11.0) installed from the deb file. Let me know if there's anything else I can help with.

Thanks!

**Comment by nathanlesage** [comment]
Huh, that sounds weird – I didn't implement anything that would trigger that behavior, and it does sound a bit odd to me. Would you mind observing how this develops, and whether you can find a way to reproduce this behavior?

**Comment by Petemir** [comment]
Hi, thanks for answering. Honestly, I don't feel confident in describing any steps because it occurs randomly (i.e. without any prior action other than navigating other apps) and constantly (i.e., whenever I start the app). 

Now that you say you never noticed this, I recalled I had this same problem with [another electron app](https://github.com/johannesjo/super-productivity/issues/2461), so it may just be something specific to my setup :) (and maybe others' setup too, as it [has been](https://github.com/electron/electron/issues/12369) [reported](https://github.com/microsoft/vscode/issues/85294) [elsewhere](https://github.com/atom/atom/issues/6828). 

Therefore, I think it's better to close this. There may be too much noise on my specific setup (5yo, multiple desktop environments and window managers installations, so on) to accurately pinpoint this. Nevertheless, I must say I wasn't able to test the app: after following the steps (downloading the appropriate models, putting them into the corresponding folder, etc.), the app could never load any of them, constantly returning an error similar to "model binary not found" or such. Thanks!
